version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "${LISTEN_PORT:-9080}:${LISTEN_PORT:-9080}"
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host ${LISTEN_IP:-0.0.0.0} --port ${LISTEN_PORT:-9080} --reload
    restart: unless-stopped

volumes:
  data:

